sudo: false
language: go
os:
  - linux
  - osx

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - master

before_script:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --force --install

script:
  - make
  - make lint
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make xc; fi

matrix:
  allow_failures:
    - go: master
  fast_finish: true
