sudo: false
language: go
os:
  - linux
  - osx

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - master

env:
  matrix:
    - TRAVIS_GOARCH=amd64
    - TRAVIS_GOARCH=386

install:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --force --install
  - export GOARCH=$TRAVIS_GOARCH
  - go env

script:
  - make isuptodate
  - make build
  - if [[ $TRAVIS_GOARCH == "amd64" ]]; then make race; fi
  - make test
  - make lint

matrix:
  allow_failures:
    - go: master
  fast_finish: true
